### ISSUE TITLE
Bug In translation (com.ubuntu.pkexec.synaptic)

### ISSUE THREAD

**Issue by GabrielMGitHub** [linuxmint/libgksu#7]
The authentication window (com.ubuntu.pkexec.synaptic) shows the title in English "Authentication is required to run synaptic packge manager", it is not being translated into Brazilian Portuguese. This package is translated in Ubuntu. IMAGE: http://imgur.com/a/7xZ8I

**Comment by GabrielMGitHub** [comment]
Report: https://bugs.launchpad.net/linuxmint/+bug/1684300

**Comment by clefebvre** [comment]
That should be a bug on synaptic instead.

https://github.com/linuxmint/synaptic
